version: "3.8"
services:
  list-reviews-db:
    container_name: list-reviews-db
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./mongo-data
        target: /data/db
volumes:
  mongo-data:
